-- MySQL Script generated by MySQL Workbench
-- Wed Jul  2 12:45:12 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema 01_anleitungDB
-- -----------------------------------------------------
-- Versuch meine Anleitungen zu Katalogiseren und in DB zu bringen

-- -----------------------------------------------------
-- Schema 01_anleitungDB
--
-- Versuch meine Anleitungen zu Katalogiseren und in DB zu bringen
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `01_anleitungDB` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `01_anleitungDB` ;

-- -----------------------------------------------------
-- Table `01_anleitungDB`.`Medium`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `01_anleitungDB`.`Medium` ;

CREATE TABLE IF NOT EXISTS `01_anleitungDB`.`Medium` (
  `idMedium` INT NOT NULL,
  `Titel` VARCHAR(150) NULL,
  `MedienArt` ENUM('Buch', 'Zeitschrift', 'Schnittmuster', 'Website', 'Flyer') NULL,
  `Mediumcol` VARCHAR(45) NULL,
  PRIMARY KEY (`idMedium`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `01_anleitungDB`.`Anleitung`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `01_anleitungDB`.`Anleitung` ;

CREATE TABLE IF NOT EXISTS `01_anleitungDB`.`Anleitung` (
  `idAnleitung` INT NOT NULL,
  `AnleitungsBezeichnung` VARCHAR(45) NULL,
  `AnleidungsNummer` VARCHAR(10) NULL,
  `Seitenzahl` INT NULL,
  `Anleitungsbogen` VARCHAR(10) NULL,
  `Grundschnitt` TINYINT NULL,
  `Standort` VARCHAR(45) NULL,
  PRIMARY KEY (`idAnleitung`),
  CONSTRAINT `idMedium`
    FOREIGN KEY (`idAnleitung`)
    REFERENCES `01_anleitungDB`.`Medium` (`idMedium`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `01_anleitungDB`.`Autor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `01_anleitungDB`.`Autor` ;

CREATE TABLE IF NOT EXISTS `01_anleitungDB`.`Autor` (
  `idAutor` INT NOT NULL,
  `AutorNachname` VARCHAR(45) NULL,
  `AutorVorname` VARCHAR(45) NULL,
  `AutorZusatz` VARCHAR(45) NULL,
  `AutorAlias` VARCHAR(45) NULL,
  PRIMARY KEY (`idAutor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `01_anleitungDB`.`Objekt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `01_anleitungDB`.`Objekt` ;

CREATE TABLE IF NOT EXISTS `01_anleitungDB`.`Objekt` (
  `idObjekt` INT NOT NULL,
  `ObjektKategorie` VARCHAR(45) NULL,
  `ObjektZweck` VARCHAR(45) NULL,
  `ObjektStyl` VARCHAR(45) NULL,
  `ObjektModel` VARCHAR(45) NULL,
  PRIMARY KEY (`idObjekt`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `01_anleitungDB`.`Technik`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `01_anleitungDB`.`Technik` ;

CREATE TABLE IF NOT EXISTS `01_anleitungDB`.`Technik` (
  `idTechnik` INT NOT NULL,
  `TechnikBereich` VARCHAR(45) NULL,
  `Methode` VARCHAR(45) NULL,
  `Arbeisweise` VARCHAR(45) NULL,
  PRIMARY KEY (`idTechnik`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `01_anleitungDB`.`Buch`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `01_anleitungDB`.`Buch` ;

CREATE TABLE IF NOT EXISTS `01_anleitungDB`.`Buch` (
  `idBuch` INT NOT NULL,
  `Untertitel` VARCHAR(150) NULL,
  `Jahr` INT NULL,
  `Verlag` VARCHAR(45) NULL,
  `Ort` VARCHAR(45) NULL,
  `ISBN` VARCHAR(45) NULL,
  `Reihe` VARCHAR(45) NULL,
  `Band` VARCHAR(45) NULL,
  PRIMARY KEY (`idBuch`),
  CONSTRAINT `idMedium`
    FOREIGN KEY (`idBuch`)
    REFERENCES `01_anleitungDB`.`Medium` (`idMedium`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `01_anleitungDB`.`Zeitschrift`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `01_anleitungDB`.`Zeitschrift` ;

CREATE TABLE IF NOT EXISTS `01_anleitungDB`.`Zeitschrift` (
  `idZeitschrift` INT NOT NULL,
  `ZeitschriftTitel` VARCHAR(45) NULL,
  `ZeitschriftUntertitel` VARCHAR(45) NULL,
  `Jahrgang` VARCHAR(45) NULL,
  `Heftnummer` VARCHAR(45) NULL,
  `Monat` VARCHAR(45) NULL,
  `Sonderheft` VARCHAR(45) NULL,
  `Thema` VARCHAR(45) NULL,
  PRIMARY KEY (`idZeitschrift`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `01_anleitungDB`.`Website`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `01_anleitungDB`.`Website` ;

CREATE TABLE IF NOT EXISTS `01_anleitungDB`.`Website` (
  `idWebsite` INT NOT NULL,
  `URL` VARCHAR(45) NULL,
  `Datum` VARCHAR(45) NULL,
  `KanalName` VARCHAR(45) NULL,
  `Dienst` VARCHAR(45) NULL,
  `Download` VARCHAR(45) NULL,
  `Ausdruck` VARCHAR(45) NULL,
  PRIMARY KEY (`idWebsite`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `01_anleitungDB`.`Flayer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `01_anleitungDB`.`Flayer` ;

CREATE TABLE IF NOT EXISTS `01_anleitungDB`.`Flayer` (
  `idFlayer` INT NOT NULL,
  `Herausgeber` VARCHAR(45) NULL,
  `Thema` VARCHAR(45) NULL,
  `FlyerNummer` VARCHAR(45) NULL,
  PRIMARY KEY (`idFlayer`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
